### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ouell** [hgmauri/RegistroBoletoOnlineBradesco#2]
Olá, tudo bem?

Segui seu modelo para implementação da rotina de registro.
Porém tanto na URL de homologação quanto na de produção... eu sempre recebo Internal Server Error.

ServicePointManager.SecurityProtocol = (SecurityProtocolType) 3072;

            var request = WebRequest.Create(uri);

            request.Method = "POST";
            request.ContentType = "application/pkcs7-signature";
            request.ContentLength = sig.Length;

            using (var requestStream = request.GetRequestStream())
            {
                requestStream.Write(sig, 0, sig.Length);
            }

            var response = request.GetResponse();

Retornar o erro quando chamo request.GetResponse

**Comment by hgmauri** [comment]
Opa, tudo bom?

Você teria mais detalhes do erro? joga aqui pra eu analisar.

...lembrando que tanto para homogação ou produção, vc precisa instalar o certificado tipo A1 e-cpf ou e-cnpj e dar permissão, se não fizer isso sempre ocorrerá erro ao consumir.

**Comment by ouell** [comment]
Opa, 

Instalei o certificado igual no link que você encaminhou na outra Issue.
Ele reconhece certinho o certificado.
Exception:

+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		HResult	-2146233088	int
		HelpLink	null	string
+		IPForWatsonBuckets	0x70d345a2	System.UIntPtr
+		InnerException	{"O servidor remoto retornou um erro: (500) Erro Interno do Servidor."}	System.Exception {System.Net.WebException}
		InnerExceptionCount	1	int
+		InnerExceptions	Count = 1	System.Collections.ObjectModel.ReadOnlyCollection<System.Exception>
		IsTransient	false	bool
		Message	"Um ou mais erros."	string
		RemoteStackTrace	null	string
		Source	"mscorlib"	string
		StackTrace	"   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   em System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   em System.Threading.Tasks.Task`1.get_Result()\r\n   em HUB.Gateway.RegistroBoleto.Saida.Helpers.BradescoHelper.EnviaParaWebService(String uri, Byte[] sig)"	string
+		TargetSite	{Void ThrowIfExceptional(Boolean)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
		WatsonBuckets	null	object

Inner:

-		InnerException	{"O servidor remoto retornou um erro: (500) Erro Interno do Servidor."}	System.Exception {System.Net.WebException}
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		HResult	-2146233079	int
		HelpLink	null	string
+		IPForWatsonBuckets	0x70d345a2	System.UIntPtr
+		InnerException	null	System.Exception
		InternalStatus	RequestFatal	System.Net.WebExceptionInternalStatus
		IsTransient	false	bool
		Message	"O servidor remoto retornou um erro: (500) Erro Interno do Servidor."	string
		RemoteStackTrace	null	string
+		Response	{System.Net.HttpWebResponse}	System.Net.WebResponse {System.Net.HttpWebResponse}
		Source	"System"	string
		StackTrace	"   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)"	string
		Status	ProtocolError	System.Net.WebExceptionStatus
+		TargetSite	{System.Net.WebResponse EndGetResponse(System.IAsyncResult)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
		WatsonBuckets	null	object
		_HResult	-2146233079	int
		_className	"System.Net.WebException"	string
+		_data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		_dynamicMethods	null	object
+		_exceptionMethod	{System.Net.WebResponse EndGetResponse(System.IAsyncResult)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
		_exceptionMethodString	null	string
		_helpURL	null	string
+		_innerException	null	System.Exception
+		_ipForWatsonBuckets	0x70d345a2	System.UIntPtr
		_message	"O servidor remoto retornou um erro: (500) Erro Interno do Servidor."	string
		_remoteStackIndex	0	int
		_remoteStackTraceString	null	string
+		_safeSerializationManager	{System.Runtime.Serialization.SafeSerializationManager}	System.Runtime.Serialization.SafeSerializationManager
		_source	"System"	string
+		_stackTrace	{sbyte[48]}	object {sbyte[]}
		_stackTraceString	null	string
		_watsonBuckets	null	object
		_xcode	-532462766	int
+		_xptrs	0x00000000	System.IntPtr
		m_InternalStatus	RequestFatal	System.Net.WebExceptionInternalStatus
+		m_Response	{System.Net.HttpWebResponse}	System.Net.WebResponse {System.Net.HttpWebResponse}
		m_Status	ProtocolError	System.Net.WebExceptionStatus

**Comment by hgmauri** [comment]
Certo, pela mensagem da pra ver que nao é certificado.

Isso ai é a mensagem que você está enviando para o web service.. ai vem o trabalho mais chato, você deve verificar em todos os campos:
- O tamanho do campo não pode ser ultrapassado
- O tipo do campo 

Sempre que ocorre o erro 500, é relacionado a estrutura da mensagem enviada!!

..se puder, pegue o seu json formatado (antes de ser criptografado) e jogue aqui (lembre de modificar os código da sua empresa)

**Comment by ouell** [comment]
Os campos numéricos eu envio "0" e os alfa "" ou " "?
Abaixo o Json:

{
    "nuCPFCNPJ": "26504594",
    "filialCPFCNPJ": "0001",
    "ctrlCPFCNPJ": "61",
    "cdTipoAcesso": "2",
    "clubBanco": "0",
    "cdTipoContrato": "0",
    "nuSequenciaContrato": "0",
    "idProduto": "09",
    "nuNegociacao": "338400000000000395",
    "cdBanco": "237",
    "eNuSequenciaContrato": "0",
    "tpRegistro": "1",
    "cdProduto": "0",
    "nuTitulo": "90",
    "nuCliente": "102030",
    "dtEmissaoTitulo": "26.02.2018",
    "dtVencimentoTitulo": "28.02.2018",
    "tpVencimento": "0",
    "vlNominalTitulo": "5000",
    "cdEspecieTitulo": "2",
    "tpProtestoAutomaticoNegativacao": "0",
    "prazoProtestoAutomaticoNegativacao": "0",
    "controleParticipante": "123645",
    "cdPagamentoParcial": "N",
    "qtdePagamentoParcial": "0",
    "percentualJuros": "0",
    "vlJuros": "0",
    "qtdeDiasJuros": "0",
    "percentualMulta": "0",
    "vlMulta": "0",
    "qtdeDiasMulta": "0",
    "percentualDesconto1": "0",
    "vlDesconto1": "0",
    "dataLimiteDesconto1": "0",
    "percentualDesconto2": "0",
    "vlDesconto2": "0",
    "dataLimiteDesconto2": "0",
    "percentualDesconto3": "0",
    "vlDesconto3": "0",
    "dataLimiteDesconto3": "0",
    "prazoBonificacao": "0",
    "percentualBonificacao": "0",
    "vlBonificacao": "0",
    "dtLimiteBonificacao": "0",
    "vlAbatimento": "0",
    "vlIOF": "0",
    "nomePagador": "Fulano da Silva dos Santos",
    "logradouroPagador": "Rua Francisco Sifroni",
    "nuLogradouroPagador": "155",
    "complementoLogradouroPagador": "0",
    "cepPagador": "78715",
    "complementoCepPagador": "668",
    "bairroPagador": "Parque Residencial Nova Era",
    "municipioPagador": "Rondonópolis",
    "ufPagador": "MT",
    "cdIndCpfcnpjPagador": "1",
    "nuCpfcnpjPagador": "81037847024",
    "endEletronicoPagador": "fulanodasilva@uol.com.br",
    "nomeSacadorAvalista": "0",
    "logradouroSacadorAvalista": "0",
    "nuLogradouroSacadorAvalista": "0",
    "complementoLogradouroSacadorAvalista": "0",
    "cepSacadorAvalista": "",
    "complementoCepSacadorAvalista": "0",
    "bairroSacadorAvalista": "0",
    "municipioSacadorAvalista": "0",
    "ufSacadorAvalista": "0",
    "cdIndCpfcnpjSacadorAvalista": "",
    "nuCpfcnpjSacadorAvalista": "",
    "endEletronicoSacadorAvalista": "0"
}

**Comment by hgmauri** [comment]
Existem erros nesse JSON..

Todos os campos inteiros que você não tem valor, tem que color "0".

Siga o exemplo abaixo, compare com o seu:

{
	"nuCPFCNPJ": "26504594",
	"filialCPFCNPJ": "0001",
	"ctrlCPFCNPJ": "61",
	"cdTipoAcesso": "2",
	"clubBanco": "0",
	"cdTipoContrato": "0",
	"nuSequenciaContrato": "364702296",
	"idProduto": "09",
	"nuNegociacao": "338400000000000395",
	"cdBanco": "237",
	"eNuSequenciaContrato": "0",
	"tpRegistro": "1",
	"cdProduto": "0",
	"nuTitulo": "36470229601",
	"nuCliente": "36470229601",
	"dtEmissaoTitulo": "26.09.2017",
	"dtVencimentoTitulo": "26.09.2017",
	"tpVencimento": "0",
	"vlNominalTitulo": "13173",
	"cdEspecieTitulo": "18",
	"tpProtestoAutomaticoNegativacao": "0",
	"prazoProtestoAutomaticoNegativacao": "0",
	"controleParticipante": "",
	"cdPagamentoParcial": "",
	"qtdePagamentoParcial": "0",
	"percentualJuros": "0",
	"vlJuros": "0",
	"qtdeDiasJuros": "0",
	"percentualMulta": "0",
	"vlMulta": "0",
	"qtdeDiasMulta": "0",
	"percentualDesconto1": "0",
	"vlDesconto1": "0",
	"dataLimiteDesconto1": "",
	"percentualDesconto2": "0",
	"vlDesconto2": "0",
	"dataLimiteDesconto2": "",
	"percentualDesconto3": "0",
	"vlDesconto3": "0",
	"dataLimiteDesconto3": "",
	"prazoBonificacao": "0",
	"percentualBonificacao": "0",
	"vlBonificacao": "0",
	"dtLimiteBonificacao": "",
	"vlAbatimento": "0",
	"vlIOF": "0",
	"nomePagador": "Fulano da Silva dos Santos",
	"logradouroPagador": "Rua Francisco Sifroni",
	"nuLogradouroPagador": "155",
	"complementoLogradouroPagador": "0",
	"cepPagador": "78715",
	"complementoCepPagador": "668",
	"bairroPagador": "Parque Residencial Nova Era",
	"municipioPagador": "Rondonópolis",
	"ufPagador": "MT",
	"cdIndCpfcnpjPagador": "1",
	"nuCpfcnpjPagador": "81037847024",
	"endEletronicoPagador": "",
	"nomeSacadorAvalista": "",
	"logradouroSacadorAvalista": "",
	"nuLogradouroSacadorAvalista": "",
	"complementoLogradouroSacadorAvalista": "",
	"cepSacadorAvalista": "0",
	"complementoCepSacadorAvalista": "0",
	"bairroSacadorAvalista": "",
	"municipioSacadorAvalista": "",
	"ufSacadorAvalista": "",
	"cdIndCpfcnpjSacadorAvalista": "0",
	"nuCpfcnpjSacadorAvalista": "0",
	"endEletronicoSacadorAvalista": ""
}

**Comment by ouell** [comment]
Fiz mais testes utilizando o seu json como exemplo para criação do meu.
Ainda retorna erro 500, porém agora no erro não tem mais InnerException onde anteriormente informava "um ou mais erros", abaixo a exception:

-		e	{"O servidor remoto retornou um erro: (500) Erro Interno do Servidor."}	System.Exception {System.Net.WebException}
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		HResult	-2146233079	int
		HelpLink	null	string
+		IPForWatsonBuckets	0x70d0d4e3	System.UIntPtr
+		InnerException	null	System.Exception
		InternalStatus	RequestFatal	System.Net.WebExceptionInternalStatus
		IsTransient	false	bool
		Message	"O servidor remoto retornou um erro: (500) Erro Interno do Servidor."	string
		RemoteStackTrace	null	string
+		Response	{System.Net.HttpWebResponse}	System.Net.WebResponse {System.Net.HttpWebResponse}
		Source	"System"	string
		StackTrace	"   em System.Net.HttpWebRequest.GetResponse()\r\n   em HUB.Gateway.RegistroBoleto.Saida.Helpers.BradescoHelper.EnviaParaWebService(String uri, Byte[] sig) na C:\\Projetos\\HUB\\HUB.Gateway.RegistroBoleto.Saida\\HUB.Gateway.RegistroBoleto.Saida\\Helpers\\BradescoHelper.cs:linha 760"	string
		Status	ProtocolError	System.Net.WebExceptionStatus
+		TargetSite	{System.Net.WebResponse GetResponse()}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
		WatsonBuckets	null	object
		_HResult	-2146233079	int
		_className	null	string
+		_data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
		_dynamicMethods	null	object
+		_exceptionMethod	{System.Net.WebResponse GetResponse()}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
		_exceptionMethodString	null	string
		_helpURL	null	string
+		_innerException	null	System.Exception
+		_ipForWatsonBuckets	0x70d0d4e3	System.UIntPtr
		_message	"O servidor remoto retornou um erro: (500) Erro Interno do Servidor."	string
		_remoteStackIndex	0	int
		_remoteStackTraceString	null	string
+		_safeSerializationManager	{System.Runtime.Serialization.SafeSerializationManager}	System.Runtime.Serialization.SafeSerializationManager
		_source	"System"	string
+		_stackTrace	{sbyte[48]}	object {sbyte[]}
		_stackTraceString	null	string
		_watsonBuckets	null	object
		_xcode	-532462766	int
+		_xptrs	0x00000000	System.IntPtr
		m_InternalStatus	RequestFatal	System.Net.WebExceptionInternalStatus
+		m_Response	{System.Net.HttpWebResponse}	System.Net.WebResponse {System.Net.HttpWebResponse}
		m_Status	ProtocolError	System.Net.WebExceptionStatus
+		Static members		


Abaixo Json enviado para solicitação:
{
    "nuCPFCNPJ": "26504594",
    "filialCPFCNPJ": "0001",
    "ctrlCPFCNPJ": "61",
    "cdTipoAcesso": "2",
    "clubBanco": "0",
    "cdTipoContrato": "0",
    "nuSequenciaContrato": "0",
    "idProduto": "09",
    "nuNegociacao": "338400000000000395",
    "cdBanco": "237",
    "eNuSequenciaContrato": "0",
    "tpRegistro": "1",
    "cdProduto": "0",
    "nuTitulo": "90",
    "nuCliente": "102030",
    "dtEmissaoTitulo": "27.02.2018",
    "dtVencimentoTitulo": "28.02.2018",
    "tpVencimento": "0",
    "vlNominalTitulo": "5000",
    "cdEspecieTitulo": "2",
    "tpProtestoAutomaticoNegativacao": "0",
    "prazoProtestoAutomaticoNegativacao": "0",
    "controleParticipante": "",
    "cdPagamentoParcial": "",
    "qtdePagamentoParcial": "0",
    "percentualJuros": "0",
    "vlJuros": "0",
    "qtdeDiasJuros": "0",
    "percentualMulta": "0",
    "vlMulta": "0",
    "qtdeDiasMulta": "0",
    "percentualDesconto1": "0",
    "vlDesconto1": "0",
    "dataLimiteDesconto1": "",
    "percentualDesconto2": "0",
    "vlDesconto2": "0",
    "dataLimiteDesconto2": "",
    "percentualDesconto3": "0",
    "vlDesconto3": "0",
    "dataLimiteDesconto3": "",
    "prazoBonificacao": "0",
    "percentualBonificacao": "0",
    "vlBonificacao": "0",
    "dtLimiteBonificacao": "",
    "vlAbatimento": "0",
    "vlIOF": "0",
    "nomePagador": "Fulano da Silva dos Santos",
    "logradouroPagador": "Rua Francisco Sifroni",
    "nuLogradouroPagador": "155",
    "complementoLogradouroPagador": "",
    "cepPagador": "78715",
    "complementoCepPagador": "668",
    "bairroPagador": "Parque Residencial Nova Era",
    "municipioPagador": "Rondonópolis",
    "ufPagador": "MT",
    "cdIndCpfcnpjPagador": "1",
    "nuCpfcnpjPagador": "81037847024",
    "endEletronicoPagador": "fulanodasilva@uol.com.br",
    "nomeSacadorAvalista": "",
    "logradouroSacadorAvalista": "",
    "nuLogradouroSacadorAvalista": "",
    "complementoLogradouroSacadorAvalista": "",
    "cepSacadorAvalista": "0",
    "complementoCepSacadorAvalista": "0",
    "bairroSacadorAvalista": "",
    "municipioSacadorAvalista": "",
    "ufSacadorAvalista": "",
    "cdIndCpfcnpjSacadorAvalista": "0",
    "nuCpfcnpjSacadorAvalista": "0",
    "endEletronicoSacadorAvalista": ""
}

**Comment by hgmauri** [comment]
Verifique o "cdEspecieTitulo".. tente colocar o 18 = FATURA e envie de novo

**Comment by ouell** [comment]
Henrique to achando que o erro não é json...
Deve ser alguma outra coisa pois, eu peguei o Json de exemplo da documentação e enviei. Também retornou erro 500. 
Json que enviei: 
{
    "nuCPFCNPJ": "123456789",
    "filialCPFCNPJ": "0001",
    "ctrlCPFCNPJ": "39",
    "cdTipoAcesso": "2",
    "clubBanco": "0",
    "cdTipoContrato": "0",
    "nuSequenciaContrato": "0",
    "idProduto": "09",
    "nuNegociacao": "123400000001234567",
    "cdBanco": "237",
    "eNuSequenciaContrato": "0",
    "tpRegistro": "1",
    "cdProduto": "0",
    "nuTitulo": "0",
    "nuCliente": "123456",
    "dtEmissaoTitulo": "25.05.2017",
    "dtVencimentoTitulo": "20.06.2017",
    "tpVencimento": "0",
    "vlNominalTitulo": "100",
    "cdEspecieTitulo": "04",
    "tpProtestoAutomaticoNegativacao": "0",
    "prazoProtestoAutomaticoNegativacao": "0",
    "controleParticipante": "",
    "cdPagamentoParcial": "",
    "qtdePagamentoParcial": "0",
    "percentualJuros": "0",
    "vlJuros": "0",
    "qtdeDiasJuros": "0",
    "percentualMulta": "0",
    "vlMulta": "0",
    "qtdeDiasMulta": "0",
    "percentualDesconto1": "0",
    "vlDesconto1": "0",
    "dataLimiteDesconto1": "",
    "percentualDesconto2": "0",
    "vlDesconto2": "0",
    "dataLimiteDesconto2": "",
    "percentualDesconto3": "0",
    "vlDesconto3": "0",
    "dataLimiteDesconto3": "",
    "prazoBonificacao": "0",
    "percentualBonificacao": "0",
    "vlBonificacao": "0",
    "dtLimiteBonificacao": "",
    "vlAbatimento": "0",
    "vlIOF": "0",
    "nomePagador": "Cliente Teste",
    "logradouroPagador": "rua Teste",
    "nuLogradouroPagador": "90",
    "complementoLogradouroPagador": "",
    "cepPagador": "12345",
    "complementoCepPagador": "500",
    "bairroPagador": "bairro Teste",
    "municipioPagador": "Teste",
    "ufPagador": "SP",
    "cdIndCpfcnpjPagador": "1",
    "nuCpfcnpjPagador": "12345648901234",
    "endEletronicoPagador": "",
    "nomeSacadorAvalista": "",
    "logradouroSacadorAvalista": "",
    "nuLogradouroSacadorAvalista": "0",
    "complementoLogradouroSacadorAvalista": "",
    "cepSacadorAvalista": "0",
    "complementoCepSacadorAvalista": "0",
    "bairroSacadorAvalista": "",
    "municipioSacadorAvalista": "",
    "ufSacadorAvalista": "",
    "cdIndCpfcnpjSacadorAvalista": "0",
    "nuCpfcnpjSacadorAvalista": "0",
    "endEletronicoSacadorAvalista": ""
}

Converti o Json assinado e retorna esses valores:
"0�\u0006\t*�H��\r\u0001\a\u0002��0�\u0002\u0001\u00011\u000f0\r\u0006\t`�H\u0001e\u0003\u0004\u0002\u0001\u0005\00�\u0006\t*�H��\r\u0001\a\u0001��$�\u0004�\u0003�{    \"nuCPFCNPJ\": \"123456789\",    \"filialCPFCNPJ\": \"0001\",    \"ctrlCPFCNPJ\": \"39\",    \"cdTipoAcesso\": \"2\",    \"clubBanco\": \"0\",    \"cdTipoContrato\": \"0\",    \"nuSequenciaContrato\": \"0\",    \"idProduto\": \"09\",    \"nuNegociacao\": \"123400000001234567\",    \"cdBanco\": \"237\",    \"eNuSequenciaContrato\": \"0\",    \"tpRegistro\": \"1\",    \"cdProduto\": \"0\",    \"nuTitulo\": \"0\",    \"nuCliente\": \"123456\",    \"dtEmissaoTitulo\": \"25.05.2017\",    \"dtVencimentoTitulo\": \"20.06.2017\",    \"tpVencimento\": \"0\",    \"vlNominalTitulo\": \"100\",    \"cdEspecieTitulo\": \"04\",    \"tpProtestoAutomaticoNegativacao\": \"0\",    \"prazoProtestoAutomaticoNegativacao\": \"0\",    \"controleParticipante\": \"\",    \"cdPagamentoParcial\": \"\",    \"qtdePagamentoParcial\": \"0\",    \"percentualJuros\": \"0\",    \"vlJuros\": \"0\",    \"qtdeDiasJuros\": \"0\",    \"percentualMulta\": \"0\",    \"vlMulta\": \"0\",    \"qtdeDiasMulta\": \"0\",    \"percentualDesconto1\": \"0\",    \"vlDesconto1\": \"0\",    \"dataLimiteDesconto1\": \"\",    \"percentualDesconto2\": \"0\",    \"vlDesconto2\"\u0004�\u0003�: \"0\",    \"dataLimiteDesconto2\": \"\",    \"percentualDesconto3\": \"0\",    \"vlDesconto3\": \"0\",    \"dataLimiteDesconto3\": \"\",    \"prazoBonificacao\": \"0\",    \"percentualBonificacao\": \"0\",    \"vlBonificacao\": \"0\",    \"dtLimiteBonificacao\": \"\",    \"vlAbatimento\": \"0\",    \"vlIOF\": \"0\",    \"nomePagador\": \"Cliente Teste\",    \"logradouroPagador\": \"rua Teste\",    \"nuLogradouroPagador\": \"90\",    \"complementoLogradouroPagador\": \"\",    \"cepPagador\": \"12345\",    \"complementoCepPagador\": \"500\",    \"bairroPagador\": \"bairro Teste\",    \"municipioPagador\": \"Teste\",    \"ufPagador\": \"SP\",    \"cdIndCpfcnpjPagador\": \"1\",    \"nuCpfcnpjPagador\": \"12345648901234\",    \"endEletronicoPagador\": \"\",    \"nomeSacadorAvalista\": \"\",    \"logradouroSacadorAvalista\": \"\",    \"nuLogradouroSacadorAvalista\": \"0\",    \"complementoLogradouroSacadorAvalista\": \"\",    \"cepSacadorAvalista\": \"0\",    \"complementoCepSacadorAvalista\": \"0\",    \"bairroSacadorAvalista\": \"\",    \"municipioSacadorAvalista\": \"\",    \"ufSacadorAvalista\": \"\",    \"cdI\u0004jndCpfcnpjSacadorAvalista\": \"0\",    \"nuCpfcnpjSacadorAvalista\": \"0\",    \"endEletronicoSacadorAvalista\": \"\"}\0\0\0\0\0\0��0�\u0002�0�\u0002:�\u0003\u0002\u0001\u0003\u0002\u0004\0���0\r\u0006\t*�H��\r\u0001\u0001\u0004\u0005\00��1\v0\t\u0006\u0003U\u0004\u0006\u0013\u0002BR1\u001c0\u001a\u0006\u0003U\u0004\n\u0013\u0013Banco Bradesco S.A.1\u00170\u0015\u0006\u0003U\u0004\v\u0013\u000eOffice Banking1\u001c0\u001a\u0006\u0003U\u0004\u0003\u0013\u0013www.bradesco.com.br1'0%\u0006\t*�H��\r\u0001\t\u0001\u0016\u0018bradesco@bradesco.com.br0\u001e\u0017\r171127154652Z\u0017\r201127154652Z0��1\u000f0\r\u0006\u0003U\u0004\u0006\u0013\u0006Brasil1\v0\t\u0006\u0003U\u0004\b\u0013\u0002SP1\u000e0\f\u0006\u0003U\u0004\a\u0013\u0005BAURU1\u001c0\u001a\u0006\u0003U\u0004\n\u0013\u0013Banco Bradesco S.A.1\u00180\u0016\u0006\u0003U\u0004\v\u0013\u000fCARTAO BRADESCO1\u001e0\u001c\u0006\u0003U\u0004\u0003\u0014\u0015CARLOS EDUARDO SIM�ES1200\u0006\t*�H��\r\u0001\t\u0001\u0016#suportearquivos@paschoalotto.com.br0��0\r\u0006\t*�H��\r\u0001\u0001\u0001\u0005\0\u0003��\00��\u0002��\0��LS\u001d[�\u0010�yP\f��\u0017�d1�F=��̀�J7��M%F�F�\u001a��~�ơ�\u0010\u001a_.�w0-�ж8��@J����.��\u0019a�A\u001bC�$�\u001b@�\n\u0013#\u0005;�\u0016˗�w���N�U�>.\u0004�$��f\u0012ϭ5\u0014�=M\u0016�I�܋����\u0015\u0003\u0002\u0003\u0001\0\u0001�\u0011\0�~Y@}`,\u000e'X#]����0\r\u0006\t*�H��\r\u0001\u0001\u0004\u0005\0\u0003��\0x{\u0012�����8�es��y��ڸL\u000eG\t�w�\u0004\">R,�N�VH��\u0003\u0017A����\u001d*�%���Y�v�F��|�ʣI��<\u0002��B�3�&\a\u000e\u0014t\u001d�4�($w0��a\u0013��|�S�F�L*\vom�\u0003ɳ\u001a\u0016;���W�@�׃n�)r��߄\0\01�\u0001�0�\u0001�\u0002\u0001\u00010��0��1\v0\t\u0006\u0003U\u0004\u0006\u0013\u0002BR1\u001c0\u001a\u0006\u0003U\u0004\n\u0013\u0013Banco Bradesco S.A.1\u00170\u0015\u0006\u0003U\u0004\v\u0013\u000eOffice Banking1\u001c0\u001a\u0006\u0003U\u0004\u0003\u0013\u0013www.bradesco.com.br1'0%\u0006\t*�H��\r\u0001\t\u0001\u0016\u0018bradesco@bradesco.com.br\u0002\u0004\0���0\r\u0006\t`�H\u0001e\u0003\u0004\u0002\u0001\u0005\0�i0\u0018\u0006\t*�H��\r\u0001\t\u00031\v\u0006\t*�H��\r\u0001\a\u00010\u001c\u0006\t*�H��\r\u0001\t\u00051\u000f\u0017\r180227135142Z0/\u0006\t*�H��\r\u0001\t\u00041\"\u0004 Vr\"\f��!�P'O��:�9�gH���w[Ju����5h0\r\u0006\t*�H��\r\u0001\u0001\v\u0005\0\u0004��t큎�j�C�s�x��\\�\u001a:F�שr�,�\u0006\u00119�Y�B?�\n�.������*\u001f��Y%�=<�E\u001f�'C�@\u0017��Q�|��\u001f\u0016H6�{�rbV=/�l\u0017��\u0001Gz��\u0014�N�LBվ�\vP�|]���R\a�L\\�]��v\u0001m[\f�78\0\0\0\0\0\0"

**Comment by hgmauri** [comment]
Pois é, o seu JSON está conforme o manual...
isso parece ser algo na sua assinatura ou certificado!

Aqui utilizamos essa aplicação pra registro de boleto online e funciona tudo corretamente

**Comment by ouell** [comment]
Utilizei esse site:
https://certlogik.com/decoder/
 pra descriptografar meu Json em base64 assinado, verifiquei uma coisa interessante olhando a Issue do BoletoNet, um rapaz postou a imagem do certificado dele validado por esse site.
No certificado do rapaz retorna as info abaixo:

Issuer: C=BR, O=ICP-Brasil, OU=Secretaria da Receita Federal do Brasil - RFB, CN=AC Cetisign RFB G5

No meu certificado retorna as informações abaixo:
Issuer: C=BR, O=Banco Bradesco S.A., OU=Office Banking, CN=www.bradesco.com.br/emailAddress=bradesco@bradesco.com.br

Creio que o financeiro da empresa me passou o certificado incorreto.

**Comment by hgmauri** [comment]
Pronto, é exatamente isso!

O certificado tem que ser ICP-Brasil

**Comment by ouell** [comment]
Henrique, 

Obrigado pela atenção e pelo tempo que você dedicou a me ajudar. 
O problema é o certificado mesmo, consegui um Json assinado na Issue do BoletoNet, enviei esse json e sua solução funcionou perfeitamente.

Muito obrigado e desculpa o trabalho e dor de cabeça.

**Comment by hgmauri** [comment]
Ótimo.

Tranquilo, qualquer coisa é só chamar

Abraço

Em 27 de fev de 2018 11:32, "Wellington Martins" <notifications@github.com>
escreveu:
