### ISSUE TITLE
Entendimento do código

### ISSUE THREAD

**Issue by Jedarc** [hgmauri/RegistroBoletoOnlineBradesco#3]
https://github.com/hgmauri/registro-boleto-online-bradesco/blob/487d4db713120cabedac5b18fb19796265247afe/BoletoOnline.Class/Uteis/MetodosUteis.cs#L329

Existe algum motivo especial para o TryParse citado acima? Apenas o `IsNullOrWhiteSpace `não seria suficiente?

**Comment by hgmauri** [comment]
@Jedarc realmente faz sentido seu comentário. Vou corrigir e subir uma nova versão.
Obrigado pela sua contribuição.
